use chrono::{DateTime, Utc};
use serde::{Deserialize, Serialize};
use uuid::Uuid;

/// Depth level for hierarchical content folding
#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
pub enum FoldLevel {
    /// Level 0: headline + 1 sentence (always visible)
    Headline = 0,
    /// Level 1: summary (3-5 sentences)
    Summary = 1,
    /// Level 2: key points and facts
    KeyPoints = 2,
    /// Level 3: full original text
    FullText = 3,
}

impl FoldLevel {
    pub fn from_u8(v: u8) -> Self {
        match v {
            0 => FoldLevel::Headline,
            1 => FoldLevel::Summary,
            2 => FoldLevel::KeyPoints,
            _ => FoldLevel::FullText,
        }
    }
}

/// A single node in the hierarchical content tree.
/// Each message gets processed into a tree of ContentNodes at different fold levels.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ContentNode {
    pub id: String,
    pub level: FoldLevel,
    pub content: String,
    pub children: Vec<ContentNode>,
}

impl ContentNode {
    pub fn new(level: FoldLevel, content: String) -> Self {
        Self {
            id: Uuid::new_v4().to_string(),
            level,
            content,
            children: Vec::new(),
        }
    }

    /// Build a complete folded tree from raw text and its LLM-generated layers.
    /// headline, summary, key_points are generated by the summarizer; full_text is the original.
    pub fn build_tree(
        headline: String,
        summary: String,
        key_points: String,
        full_text: String,
    ) -> Self {
        let full = ContentNode::new(FoldLevel::FullText, full_text);
        let mut keys = ContentNode::new(FoldLevel::KeyPoints, key_points);
        keys.children.push(full);
        let mut summ = ContentNode::new(FoldLevel::Summary, summary);
        summ.children.push(keys);
        let mut head = ContentNode::new(FoldLevel::Headline, headline);
        head.children.push(summ);
        head
    }
}

/// Represents a processed Telegram message with its folded content tree
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ProcessedMessage {
    /// Unique ID within hydra-content
    pub id: String,
    /// Telegram chat/channel ID
    pub chat_id: i64,
    /// Telegram message ID
    pub message_id: i32,
    /// Chat/channel title
    pub chat_title: String,
    /// Sender name
    pub sender_name: String,
    /// Original message timestamp
    pub timestamp: DateTime<Utc>,
    /// Hierarchical content tree (root = Headline level)
    pub content_tree: ContentNode,
    /// Whether this message is from a private/closed source (processed on-device only)
    pub is_private: bool,
}

/// Tracks user attention on a specific content node
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct AttentionEvent {
    /// Which processed message
    pub message_id: String,
    /// Chat/channel ID
    pub chat_id: i64,
    /// Maximum fold depth the user expanded to
    pub max_depth_reached: u8,
    /// Total reading time in milliseconds
    pub total_read_time_ms: u64,
    /// Type of interaction
    pub interaction: InteractionType,
    /// When the interaction happened
    pub timestamp: DateTime<Utc>,
}

/// Categorization of user interaction depth
#[derive(Debug, Clone, Copy, Serialize, Deserialize)]
pub enum InteractionType {
    /// Saw headline only, scrolled past
    Skim,
    /// Expanded to summary level
    Read,
    /// Expanded to key points or full text
    DeepDive,
    /// Shared or forwarded
    Share,
}

/// Info about a Telegram chat/channel tracked by hydra-content
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct TrackedChat {
    /// Telegram chat ID
    pub chat_id: i64,
    /// Chat title
    pub title: String,
    /// Whether it's a private chat/group (processed on-device only)
    pub is_private: bool,
    /// Whether content processing is enabled for this chat
    pub processing_enabled: bool,
}
