// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `cache_resolution`, `connection_cache`, `connection_key`, `queue_resolution`, `take_completed_resolutions`, `take_pending_resolution_requests`, `to_core`, `uid_cache`
// These types are ignored because they are neither used by any `pub` functions nor (for structs and enums) marked `#[frb(unignore)]`: `COMPLETED_RESOLUTIONS`, `MobileAppResolver`, `PENDING_RESOLUTIONS`, `PendingAppResolution`, `SubmittedAppResolution`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `assert_receiver_is_total_eq`, `clone`, `clone`, `clone`, `deref`, `deref`, `eq`, `fmt`, `fmt`, `fmt`, `initialize`, `initialize`, `resolve_app`

Future<CoreAppAttribution?> resolveAppForConnection({
  required int protocol,
  required String localIp,
  required int localPort,
  required String remoteIp,
  required int remotePort,
}) => RustLib.instance.api.crateApiAppResolverResolveAppForConnection(
  protocol: protocol,
  localIp: localIp,
  localPort: localPort,
  remoteIp: remoteIp,
  remotePort: remotePort,
);

Future<AppAttribution?> getCachedAttribution({
  required String host,
  required int port,
}) => RustLib.instance.api.crateApiAppResolverGetCachedAttribution(
  host: host,
  port: port,
);

Future<void> cacheAttribution({
  required String host,
  required int port,
  required AppAttribution attribution,
}) => RustLib.instance.api.crateApiAppResolverCacheAttribution(
  host: host,
  port: port,
  attribution: attribution,
);

Future<AppAttribution?> parseAttributionJson({required String json}) =>
    RustLib.instance.api.crateApiAppResolverParseAttributionJson(json: json);

Future<bool> cacheAttributionFromJson({
  required String host,
  required int port,
  required String json,
}) => RustLib.instance.api.crateApiAppResolverCacheAttributionFromJson(
  host: host,
  port: port,
  json: json,
);

Future<(BigInt, BigInt)> cacheStats() =>
    RustLib.instance.api.crateApiAppResolverCacheStats();

Future<void> requestResolution({required String host, required int port}) =>
    RustLib.instance.api.crateApiAppResolverRequestResolution(
      host: host,
      port: port,
    );

Future<List<(String, int)>> takePendingResolutions() =>
    RustLib.instance.api.crateApiAppResolverTakePendingResolutions();

String getPendingAppResolutions() =>
    RustLib.instance.api.crateApiAppResolverGetPendingAppResolutions();

bool submitAppResolution({
  required String host,
  required int port,
  required String json,
}) => RustLib.instance.api.crateApiAppResolverSubmitAppResolution(
  host: host,
  port: port,
  json: json,
);

String getCachedAppAttribution({required String host, required int port}) =>
    RustLib.instance.api.crateApiAppResolverGetCachedAppAttribution(
      host: host,
      port: port,
    );

String getAppCacheStats() =>
    RustLib.instance.api.crateApiAppResolverGetAppCacheStats();

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<CoreAppAttribution>>
abstract class CoreAppAttribution implements RustOpaqueInterface {}

class AppAttribution {
  final int uid;
  final String? packageName;
  final String? appLabel;

  const AppAttribution({required this.uid, this.packageName, this.appLabel});

  Future<bool> isValid() =>
      RustLib.instance.api.crateApiAppResolverAppAttributionIsValid(that: this);

  static Future<AppAttribution> unknown() =>
      RustLib.instance.api.crateApiAppResolverAppAttributionUnknown();

  @override
  int get hashCode => uid.hashCode ^ packageName.hashCode ^ appLabel.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is AppAttribution &&
          runtimeType == other.runtimeType &&
          uid == other.uid &&
          packageName == other.packageName &&
          appLabel == other.appLabel;
}
