// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `auth_state_to_string`
// These types are ignored because they are neither used by any `pub` functions nor (for structs and enums) marked `#[frb(unignore)]`: `CONTENT_ENGINE`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `deref`, `initialize`

/// Initialize the Content Engine. Called after start_hydra_node when config is ready.
Future<void> initContentEngine({required String baseDir}) =>
    RustLib.instance.api.crateApiContentInitContentEngine(baseDir: baseDir);

/// Connect to Telegram. Returns the current auth state as a string.
Future<String> telegramConnect() =>
    RustLib.instance.api.crateApiContentTelegramConnect();

/// Send phone number for Telegram login. Returns auth state.
Future<String> telegramSendPhone({required String phone}) =>
    RustLib.instance.api.crateApiContentTelegramSendPhone(phone: phone);

/// Send login code for Telegram auth. Returns auth state.
Future<String> telegramSendCode({required String code}) =>
    RustLib.instance.api.crateApiContentTelegramSendCode(code: code);

/// Send 2FA password. Returns auth state.
Future<String> telegramSendPassword({required String password}) => RustLib
    .instance
    .api
    .crateApiContentTelegramSendPassword(password: password);

/// Get Telegram auth state as a string.
Future<String> telegramAuthState() =>
    RustLib.instance.api.crateApiContentTelegramAuthState();

/// Get list of Telegram dialogs (chats, groups, channels).
/// Returns JSON array of TrackedChat objects.
Future<String> telegramGetDialogs() =>
    RustLib.instance.api.crateApiContentTelegramGetDialogs();

/// Record an attention event from the Flutter UI.
/// Called when user expands/reads content.
Future<void> recordAttention({
  required String messageId,
  required PlatformInt64 chatId,
  required int maxDepth,
  required BigInt readTimeMs,
  required String interaction,
}) => RustLib.instance.api.crateApiContentRecordAttention(
  messageId: messageId,
  chatId: chatId,
  maxDepth: maxDepth,
  readTimeMs: readTimeMs,
  interaction: interaction,
);

/// Get attention statistics for a chat. Returns JSON.
Future<String> getChatAttentionStats({required PlatformInt64 chatId}) =>
    RustLib.instance.api.crateApiContentGetChatAttentionStats(chatId: chatId);

/// Disconnect from Telegram.
Future<void> telegramDisconnect() =>
    RustLib.instance.api.crateApiContentTelegramDisconnect();

/// Fetch messages from a specific chat with summarization.
/// Returns JSON array of ProcessedMessage with fold levels.
/// Stub pending FRB codegen.
Future<String> fetchChannelMessages({required int chatId, required int limit}) async {
  // TODO: replace with RustLib.instance.api.crateApiContentFetchChannelMessages(...)
  return '[]';
}
