// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

void dismissNudge({required String nudgeId}) =>
    RustLib.instance.api.crateApiCreditDismissNudge(nudgeId: nudgeId);

Future<String> getCreditStatus() =>
    RustLib.instance.api.crateApiCreditGetCreditStatus();

Future<String> getNudge() => RustLib.instance.api.crateApiCreditGetNudge();

Future<String> acceptTrialRoute() =>
    RustLib.instance.api.crateApiCreditAcceptTrialRoute();

Future<String> getTelegramAnchorInfo() =>
    RustLib.instance.api.crateApiCreditGetTelegramAnchorInfo();
