// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// Write a Dart-side event into the shared log timeline (file + live view).
void logMessage(
        {required String level,
        required String target,
        required String message}) =>
    RustLib.instance.api.crateApiDiagnosticsLogMessage(
        level: level, target: target, message: message);

String? logDirectory() =>
    RustLib.instance.api.crateApiDiagnosticsLogDirectory();

/// Session log files, newest first.
List<String> listLogFiles() =>
    RustLib.instance.api.crateApiDiagnosticsListLogFiles();

/// Write a self-contained diagnostics report (status, redacted servers,
/// recent log lines) next to the logs and return its path.
Future<String> writeDiagnosticsReport({required String appInfo}) =>
    RustLib.instance.api
        .crateApiDiagnosticsWriteDiagnosticsReport(appInfo: appInfo);
