// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `disabled`, `incomplete`, `load_exchange_config`, `ready`, `to_json`
// These types are ignored because they are neither used by any `pub` functions nor (for structs and enums) marked `#[frb(unignore)]`: `MarketplaceConfigStatus`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `fmt`

String getMarketplaceConfigStatus() =>
    RustLib.instance.api.crateApiExchangeGetMarketplaceConfigStatus();

String createWallet() => RustLib.instance.api.crateApiExchangeCreateWallet();

String getWalletPreview({required String mnemonic}) =>
    RustLib.instance.api.crateApiExchangeGetWalletPreview(mnemonic: mnemonic);

String importWallet({required String mnemonic}) =>
    RustLib.instance.api.crateApiExchangeImportWallet(mnemonic: mnemonic);

Future<String> getWalletBalances({required String address}) =>
    RustLib.instance.api.crateApiExchangeGetWalletBalances(address: address);

Future<String> listRouteOffers({
  required String region,
  required String protocol,
}) => RustLib.instance.api.crateApiExchangeListRouteOffers(
  region: region,
  protocol: protocol,
);

Future<String> registerAgent({required String mnemonic}) =>
    RustLib.instance.api.crateApiExchangeRegisterAgent(mnemonic: mnemonic);

Future<String> submitFeedback({
  required String mnemonic,
  required BigInt agentId,
  required bool positive,
  required String tag1,
}) => RustLib.instance.api.crateApiExchangeSubmitFeedback(
  mnemonic: mnemonic,
  agentId: agentId,
  positive: positive,
  tag1: tag1,
);
