// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These types are ignored because they are neither used by any `pub` functions nor (for structs and enums) marked `#[frb(unignore)]`: `MANAGER`, `ModelManager`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `deref`, `fmt`, `initialize`

void initModelManager({required String baseDir}) =>
    RustLib.instance.api.crateApiModelManagerInitModelManager(baseDir: baseDir);

Future<List<ModelInfo>> getAvailableModels() =>
    RustLib.instance.api.crateApiModelManagerGetAvailableModels();

Stream<double> downloadModel({required String id}) =>
    RustLib.instance.api.crateApiModelManagerDownloadModel(id: id);

Future<void> setActiveModel({required String id}) =>
    RustLib.instance.api.crateApiModelManagerSetActiveModel(id: id);

class ModelInfo {
  final String id;
  final String name;
  final String description;
  final int sizeMb;
  final String downloadUrl;
  final bool isDownloaded;

  const ModelInfo({
    required this.id,
    required this.name,
    required this.description,
    required this.sizeMb,
    required this.downloadUrl,
    required this.isDownloaded,
  });

  @override
  int get hashCode =>
      id.hashCode ^
      name.hashCode ^
      description.hashCode ^
      sizeMb.hashCode ^
      downloadUrl.hashCode ^
      isDownloaded.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ModelInfo &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          name == other.name &&
          description == other.description &&
          sizeMb == other.sizeMb &&
          downloadUrl == other.downloadUrl &&
          isDownloaded == other.isDownloaded;
}
