// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

Future<String> getShareEarnStatus() =>
    RustLib.instance.api.crateApiProviderGetShareEarnStatus();

Future<String> setShareEarnEnabled({required bool enabled, String? mnemonic}) =>
    RustLib.instance.api.crateApiProviderSetShareEarnEnabled(
      enabled: enabled,
      mnemonic: mnemonic,
    );

Future<String> getProviderEarnings() =>
    RustLib.instance.api.crateApiProviderGetProviderEarnings();

Future<String> updateShareSettings({
  String? priceOverrideRaw,
  BigInt? maxBandwidthMbps,
  required bool wifiOnly,
  int? scheduleStartHour,
  int? scheduleEndHour,
}) => RustLib.instance.api.crateApiProviderUpdateShareSettings(
  priceOverrideRaw: priceOverrideRaw,
  maxBandwidthMbps: maxBandwidthMbps,
  wifiOnly: wifiOnly,
  scheduleStartHour: scheduleStartHour,
  scheduleEndHour: scheduleEndHour,
);
