// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// Initialize the quota system with relay URL and device ID.
Future<void> initQuota({required String relayUrl, required String deviceId}) =>
    RustLib.instance.api.crateApiQuotaInitQuota(
      relayUrl: relayUrl,
      deviceId: deviceId,
    );

/// Record bytes consumed locally (called from relay/proxy layer).
Future<void> recordBytes({required BigInt bytes}) =>
    RustLib.instance.api.crateApiQuotaRecordBytes(bytes: bytes);

/// Get current quota status as JSON string.
/// Returns: {"used": N, "limit": M, "remaining": R, "resets_at": "..."}
Future<String> getQuotaStatus() =>
    RustLib.instance.api.crateApiQuotaGetQuotaStatus();

/// Sync local quota with the server. Returns updated quota JSON.
Future<String> syncQuotaWithServer() =>
    RustLib.instance.api.crateApiQuotaSyncQuotaWithServer();

/// Reset daily quota counter.
Future<void> resetDailyQuota() =>
    RustLib.instance.api.crateApiQuotaResetDailyQuota();

/// Get raw quota values for testing/UI.
Future<(BigInt, BigInt)> getQuotaRaw() =>
    RustLib.instance.api.crateApiQuotaGetQuotaRaw();
