// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `attach_runtime_handles`, `bootstrap`, `build_imported_vless_profile`, `current_hour_bucket`, `current_profiles`, `decode_base64_relaxed`, `history`, `kind_name`, `load_or_seed_profiles`, `load_policies`, `load`, `next_priority`, `normalize_profile`, `normalize_profiles`, `now_epoch_millis`, `now_epoch_secs`, `parse_group_kind`, `parse_policy_action`, `parse_raw_payload`, `parse_subscription_payload`, `persist_json`, `persist_profiles_locked`, `profile_url`, `record_wss_usage`, `reload_from_disk`, `renumber_priorities`, `seed_profiles`, `sort_profiles`, `start_of_day`, `summary`, `sync_transports_locked`, `to_json`, `with_state_mut`, `with_state`
// These types are ignored because they are neither used by any `pub` functions nor (for structs and enums) marked `#[frb(unignore)]`: `ImportReport`, `ROUTE_RUNTIME`, `RelayUsageSample`, `RelayUsageStore`, `RelayUsageSummary`, `RouteRuntimeState`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `clone`, `clone`, `deref`, `fmt`, `fmt`, `fmt`, `fmt`, `initialize`, `record_usage`

Future<String> listRouteProfiles() =>
    RustLib.instance.api.crateApiRoutesListRouteProfiles();

Future<String> importRouteProfiles({
  required String payload,
  required String importFormat,
}) => RustLib.instance.api.crateApiRoutesImportRouteProfiles(
  payload: payload,
  importFormat: importFormat,
);

Future<String> updateRouteProfile({required String profileJson}) => RustLib
    .instance
    .api
    .crateApiRoutesUpdateRouteProfile(profileJson: profileJson);

Future<void> deleteRouteProfile({required String profileId}) =>
    RustLib.instance.api.crateApiRoutesDeleteRouteProfile(profileId: profileId);

Future<String> reorderRouteProfiles({required String profileIdsJson}) => RustLib
    .instance
    .api
    .crateApiRoutesReorderRouteProfiles(profileIdsJson: profileIdsJson);

Future<String> listRoutePolicies() =>
    RustLib.instance.api.crateApiRoutesListRoutePolicies();

Future<String> setRoutePolicy({
  required String groupKind,
  required String groupKey,
  required String action,
  required String profileId,
}) => RustLib.instance.api.crateApiRoutesSetRoutePolicy(
  groupKind: groupKind,
  groupKey: groupKey,
  action: action,
  profileId: profileId,
);

Future<void> clearRoutePolicy({
  required String groupKind,
  required String groupKey,
}) => RustLib.instance.api.crateApiRoutesClearRoutePolicy(
  groupKind: groupKind,
  groupKey: groupKey,
);

/// Create an SSH route profile.
/// auth_type: "password", "key_pem", or "key_file"
/// credential: password string, PEM key content, or file path (depending on auth_type)
Future<String> createSshRouteProfile({
  required String host,
  required int port,
  required String username,
  required String authType,
  required String credential,
}) => RustLib.instance.api.crateApiRoutesCreateSshRouteProfile(
  host: host,
  port: port,
  username: username,
  authType: authType,
  credential: credential,
);

Future<String> getRelayUsageSummary() =>
    RustLib.instance.api.crateApiRoutesGetRelayUsageSummary();

Future<String> getRelayUsageHistory({required int days}) =>
    RustLib.instance.api.crateApiRoutesGetRelayUsageHistory(days: days);
