// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `last_error`, `now_ms`, `running_transports`, `set_last_error`, `snapshot_transports`, `start_inner`, `warm_up_transports`
// These types are ignored because they are neither used by any `pub` functions nor (for structs and enums) marked `#[frb(unignore)]`: `ProxyStatus`, `RouteStatus`, `RunningNode`

String greet({required String name}) =>
    RustLib.instance.api.crateApiSimpleGreet(name: name);

/// Install logging. `log_dir` enables persistent, rotating log files.
/// Safe to call more than once (later calls only add the file sink if missing).
void initApp({String? logDir}) =>
    RustLib.instance.api.crateApiSimpleInitApp(logDir: logDir);

Future<void> initExtensionRuntime({required String baseDir}) =>
    RustLib.instance.api.crateApiSimpleInitExtensionRuntime(baseDir: baseDir);

Future<void> prepareLocalRuntime({required String baseDir}) =>
    RustLib.instance.api.crateApiSimplePrepareLocalRuntime(baseDir: baseDir);

/// Start the local SOCKS5 server (127.0.0.1:<socks5_port>) over the enabled
/// route profiles. Idempotent. Returns an error if the port cannot be bound.
Future<void> startHydraNode({required String baseDir}) =>
    RustLib.instance.api.crateApiSimpleStartHydraNode(baseDir: baseDir);

/// Stop the SOCKS5 server and drop SSH sessions.
Future<void> stopHydraNode() =>
    RustLib.instance.api.crateApiSimpleStopHydraNode();

/// Drop and re-establish long-lived transport sessions. Call after network
/// changes or when returning to the foreground.
Future<void> reconnectTransports({required String reason}) =>
    RustLib.instance.api.crateApiSimpleReconnectTransports(reason: reason);

/// JSON snapshot for the UI; cheap enough to poll every second.
Future<String> getProxyStatus() =>
    RustLib.instance.api.crateApiSimpleGetProxyStatus();

/// Set proxy mode at runtime. Values: "off", "telegram", "full".
Future<void> setProxyMode({required String mode}) =>
    RustLib.instance.api.crateApiSimpleSetProxyMode(mode: mode);

/// Get SOCKS5 proxy listen port.
int getSocks5Port() => RustLib.instance.api.crateApiSimpleGetSocks5Port();

/// True while the SOCKS5 server task is alive.
bool isNodeRunning() => RustLib.instance.api.crateApiSimpleIsNodeRunning();

/// Execute a shell command on the device.
/// Returns JSON: { "exit_code": N|null, "stdout": "...", "stderr": "...", "truncated": bool, "timed_out": bool }
///
/// Only read-only inspection commands are allowed (ls, cat, ps, etc.).
/// Destructive commands (rm, kill, reboot, etc.) are blocked.
Future<String> shellExec({required String command}) =>
    RustLib.instance.api.crateApiSimpleShellExec(command: command);

/// Execute multiple shell commands sequentially.
/// Returns JSON array of results.
Future<String> shellExecBatch({required List<String> commands}) =>
    RustLib.instance.api.crateApiSimpleShellExecBatch(commands: commands);

/// Collect a full network inspection from the device.
Future<String> inspectDeviceNetwork() =>
    RustLib.instance.api.crateApiSimpleInspectDeviceNetwork();

/// Quick one-line network summary: established/listening TCP counts + top UIDs.
Future<String> quickNetworkSummary() =>
    RustLib.instance.api.crateApiSimpleQuickNetworkSummary();
