// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `ensure_snapshot_writer`
// These types are ignored because they are neither used by any `pub` functions nor (for structs and enums) marked `#[frb(unignore)]`: `NODE_STARTED`, `SHARED_REGISTRY`, `SHARED_RELAY_MODE`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `deref`, `deref`, `deref`, `initialize`, `initialize`, `initialize`

String greet({required String name}) =>
    RustLib.instance.api.crateApiSimpleGreet(name: name);

Future<void> initApp() => RustLib.instance.api.crateApiSimpleInitApp();

Future<void> initExtensionRuntime({required String baseDir}) =>
    RustLib.instance.api.crateApiSimpleInitExtensionRuntime(baseDir: baseDir);

Future<void> prepareLocalRuntime({required String baseDir}) =>
    RustLib.instance.api.crateApiSimplePrepareLocalRuntime(baseDir: baseDir);

Future<void> startHydraNode({required String baseDir}) =>
    RustLib.instance.api.crateApiSimpleStartHydraNode(baseDir: baseDir);

/// Get active connections as JSON for Flutter UI.
Future<String> getActiveConnections() =>
    RustLib.instance.api.crateApiSimpleGetActiveConnections();

/// Get connection stats summary as JSON.
Future<String> getConnectionStats() =>
    RustLib.instance.api.crateApiSimpleGetConnectionStats();

/// Toggle proxy for a specific connection.
Future<void> setConnectionProxy({
  required BigInt connId,
  required bool proxied,
}) => RustLib.instance.api.crateApiSimpleSetConnectionProxy(
  connId: connId,
  proxied: proxied,
);

/// Set proxy mode at runtime. Values: "off", "telegram", "full".
/// Called from Flutter Settings when user changes proxy mode.
Future<void> setProxyMode({required String mode}) =>
    RustLib.instance.api.crateApiSimpleSetProxyMode(mode: mode);

/// Async LLM analysis of connection security/quality.
/// Accepts a JSON description of connections, returns LLM text recommendation.
/// Returns a fallback message if AI model is not loaded (instead of erroring).
Future<String> analyzeConnections({required String connectionsJson}) => RustLib
    .instance
    .api
    .crateApiSimpleAnalyzeConnections(connectionsJson: connectionsJson);

/// Async LLM analysis for a single host — security recommendation.
/// Returns a fallback message if AI model is not loaded (instead of erroring).
Future<String> analyzeHost({
  required String host,
  required int port,
  required bool isProxied,
  required BigInt bytesTotal,
}) => RustLib.instance.api.crateApiSimpleAnalyzeHost(
  host: host,
  port: port,
  isProxied: isProxied,
  bytesTotal: bytesTotal,
);
