// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: unused_import, unused_element, unnecessary_import, duplicate_ignore, invalid_use_of_internal_member, annotate_overrides, non_constant_identifier_names, curly_braces_in_flow_control_structures, prefer_const_literals_to_create_immutables, unused_field

import 'api/content.dart';
import 'api/credit.dart';
import 'api/exchange.dart';
import 'api/model_manager.dart';
import 'api/provider.dart';
import 'api/quota.dart';
import 'api/shared_state.dart';
import 'api/simple.dart';
import 'api/telemetry.dart';
import 'api/vpn.dart';
import 'dart:async';
import 'dart:convert';
import 'frb_generated.dart';
import 'frb_generated.io.dart'
    if (dart.library.js_interop) 'frb_generated.web.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// Main entrypoint of the Rust API
class RustLib extends BaseEntrypoint<RustLibApi, RustLibApiImpl, RustLibWire> {
  @internal
  static final instance = RustLib._();

  RustLib._();

  /// Initialize flutter_rust_bridge
  static Future<void> init({
    RustLibApi? api,
    BaseHandler? handler,
    ExternalLibrary? externalLibrary,
    bool forceSameCodegenVersion = true,
  }) async {
    await instance.initImpl(
      api: api,
      handler: handler,
      externalLibrary: externalLibrary,
      forceSameCodegenVersion: forceSameCodegenVersion,
    );
  }

  /// Initialize flutter_rust_bridge in mock mode.
  /// No libraries for FFI are loaded.
  static void initMock({required RustLibApi api}) {
    instance.initMockImpl(api: api);
  }

  /// Dispose flutter_rust_bridge
  ///
  /// The call to this function is optional, since flutter_rust_bridge (and everything else)
  /// is automatically disposed when the app stops.
  static void dispose() => instance.disposeImpl();

  @override
  ApiImplConstructor<RustLibApiImpl, RustLibWire> get apiImplConstructor =>
      RustLibApiImpl.new;

  @override
  WireConstructor<RustLibWire> get wireConstructor =>
      RustLibWire.fromExternalLibrary;

  @override
  Future<void> executeRustInitializers() async {}

  @override
  ExternalLibraryLoaderConfig get defaultExternalLibraryLoaderConfig =>
      kDefaultExternalLibraryLoaderConfig;

  @override
  String get codegenVersion => '2.11.1';

  @override
  int get rustContentHash => 1358170129;

  static const kDefaultExternalLibraryLoaderConfig =
      ExternalLibraryLoaderConfig(
        stem: 'rust_lib_hydra_mobile',
        ioDirectory: 'rust/target/release/',
        webPrefix: 'pkg/',
      );
}

abstract class RustLibApi extends BaseApi {
  Future<String> crateApiExchangeAcceptDeal({
    required String mnemonic,
    required BigInt offerId,
    required String usdcAmount,
  });

  Future<String> crateApiCreditAcceptTrialRoute();

  Future<String> crateApiSimpleAnalyzeConnections({
    required String connectionsJson,
  });

  Future<String> crateApiSimpleAnalyzeHost({
    required String host,
    required int port,
    required bool isProxied,
    required BigInt bytesTotal,
  });

  Future<void> crateApiSharedStateAppendLogLine({required String line});

  Future<String> crateApiExchangeApproveDealBoardUsdc({
    required String mnemonic,
    required String amount,
  });

  Future<String> crateApiExchangeCheckEscrowStatus({required BigInt escrowId});

  Future<String> crateApiExchangeClaimExpiredEscrow({
    required String mnemonic,
    required BigInt escrowId,
  });

  Stream<String> crateApiTelemetryCreateLogStream();

  Future<String> crateApiExchangeCreateOffer({
    required String mnemonic,
    required BigInt agentId,
    required String endpointUrl,
    required List<String> protocols,
    required String region,
    required String pricePerGbRaw,
    required String stakeAmountRaw,
    required BigInt bandwidthMbps,
  });

  String crateApiExchangeCreateWallet();

  Future<String> crateApiExchangeDeactivateOffer({
    required String mnemonic,
    required BigInt offerId,
  });

  void crateApiCreditDismissNudge({required String nudgeId});

  Stream<double> crateApiModelManagerDownloadModel({required String id});

  Future<String> crateApiContentFetchChannelMessages({
    required PlatformInt64 chatId,
    required int limit,
  });

  Future<String> crateApiSimpleGetActiveConnections();

  Future<List<ModelInfo>> crateApiModelManagerGetAvailableModels();

  Future<String> crateApiContentGetChatAttentionStats({
    required PlatformInt64 chatId,
  });

  Future<String> crateApiSimpleGetConnectionStats();

  Future<String> crateApiCreditGetCreditStatus();

  Future<String> crateApiExchangeGetDealOffer({required BigInt offerId});

  String crateApiExchangeGetMarketplaceConfigStatus();

  Future<String> crateApiContentGetMessageFoldContent({
    required String contentTreeJson,
    required int level,
  });

  Future<String> crateApiCreditGetNudge();

  Future<String> crateApiProviderGetProviderEarnings();

  Future<(BigInt, BigInt)> crateApiQuotaGetQuotaRaw();

  Future<String> crateApiQuotaGetQuotaStatus();

  Future<String> crateApiProviderGetShareEarnStatus();

  Future<String> crateApiCreditGetTelegramAnchorInfo();

  Future<String> crateApiExchangeGetWalletBalances({required String address});

  String crateApiExchangeGetWalletPreview({required String mnemonic});

  String crateApiSimpleGreet({required String name});

  String crateApiExchangeImportWallet({required String mnemonic});

  Future<void> crateApiSimpleInitApp();

  Future<void> crateApiContentInitContentEngine({required String baseDir});

  Future<void> crateApiSimpleInitExtensionRuntime({required String baseDir});

  void crateApiModelManagerInitModelManager({required String baseDir});

  Future<void> crateApiQuotaInitQuota({
    required String relayUrl,
    required String deviceId,
  });

  Future<String> crateApiExchangeListDealOffers({required String currency});

  Future<String> crateApiExchangeListRouteOffers({
    required String region,
    required String protocol,
  });

  Future<String> crateApiExchangeMarkFiatSent({
    required String mnemonic,
    required BigInt escrowId,
  });

  Future<void> crateApiSharedStatePersistActiveConnections({
    required String json,
  });

  Future<void> crateApiSharedStatePersistConnectionStats({
    required String json,
  });

  Future<void> crateApiSharedStatePersistQuotaStatus({required String json});

  Future<void> crateApiSimplePrepareLocalRuntime({required String baseDir});

  Future<List<String>> crateApiSharedStateReadLogLines();

  Future<void> crateApiContentRecordAttention({
    required String messageId,
    required PlatformInt64 chatId,
    required int maxDepth,
    required BigInt readTimeMs,
    required String interaction,
  });

  Future<void> crateApiQuotaRecordBytes({required BigInt bytes});

  Future<String> crateApiExchangeRegisterAgent({required String mnemonic});

  Future<void> crateApiQuotaResetDailyQuota();

  Future<void> crateApiModelManagerSetActiveModel({required String id});

  Future<void> crateApiSimpleSetConnectionProxy({
    required BigInt connId,
    required bool proxied,
  });

  Future<void> crateApiSimpleSetProxyMode({required String mode});

  Future<String> crateApiProviderSetShareEarnEnabled({
    required bool enabled,
    String? mnemonic,
  });

  Future<String> crateApiSharedStateSnapshotJson();

  Future<void> crateApiSimpleStartHydraNode({required String baseDir});

  void crateApiVpnStartVpnTunnel({required int fd});

  void crateApiVpnStopVpnTunnel();

  Future<String> crateApiExchangeSubmitFeedback({
    required String mnemonic,
    required BigInt agentId,
    required bool positive,
    required String tag1,
  });

  Future<String> crateApiQuotaSyncQuotaWithServer();

  Future<String> crateApiContentTelegramAuthState();

  Future<String> crateApiContentTelegramConnect();

  Future<void> crateApiContentTelegramDisconnect();

  Future<String> crateApiContentTelegramGetDialogs();

  Future<String> crateApiContentTelegramSendCode({required String code});

  Future<String> crateApiContentTelegramSendPassword({
    required String password,
  });

  Future<String> crateApiContentTelegramSendPhone({required String phone});

  Future<String> crateApiProviderUpdateShareSettings({
    String? priceOverrideRaw,
    BigInt? maxBandwidthMbps,
    required bool wifiOnly,
    int? scheduleStartHour,
    int? scheduleEndHour,
  });

  Future<String> crateApiExchangeWithdrawStake({
    required String mnemonic,
    required BigInt offerId,
  });
}

class RustLibApiImpl extends RustLibApiImplPlatform implements RustLibApi {
  RustLibApiImpl({
    required super.handler,
    required super.wire,
    required super.generalizedFrbRustBinding,
    required super.portManager,
  });

  @override
  Future<String> crateApiExchangeAcceptDeal({
    required String mnemonic,
    required BigInt offerId,
    required String usdcAmount,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(mnemonic, serializer);
          sse_encode_u_64(offerId, serializer);
          sse_encode_String(usdcAmount, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 1,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiExchangeAcceptDealConstMeta,
        argValues: [mnemonic, offerId, usdcAmount],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiExchangeAcceptDealConstMeta => const TaskConstMeta(
    debugName: "accept_deal",
    argNames: ["mnemonic", "offerId", "usdcAmount"],
  );

  @override
  Future<String> crateApiCreditAcceptTrialRoute() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 2,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiCreditAcceptTrialRouteConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiCreditAcceptTrialRouteConstMeta =>
      const TaskConstMeta(debugName: "accept_trial_route", argNames: []);

  @override
  Future<String> crateApiSimpleAnalyzeConnections({
    required String connectionsJson,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(connectionsJson, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 3,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiSimpleAnalyzeConnectionsConstMeta,
        argValues: [connectionsJson],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSimpleAnalyzeConnectionsConstMeta =>
      const TaskConstMeta(
        debugName: "analyze_connections",
        argNames: ["connectionsJson"],
      );

  @override
  Future<String> crateApiSimpleAnalyzeHost({
    required String host,
    required int port,
    required bool isProxied,
    required BigInt bytesTotal,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(host, serializer);
          sse_encode_u_16(port, serializer);
          sse_encode_bool(isProxied, serializer);
          sse_encode_u_64(bytesTotal, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 4,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiSimpleAnalyzeHostConstMeta,
        argValues: [host, port, isProxied, bytesTotal],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSimpleAnalyzeHostConstMeta => const TaskConstMeta(
    debugName: "analyze_host",
    argNames: ["host", "port", "isProxied", "bytesTotal"],
  );

  @override
  Future<void> crateApiSharedStateAppendLogLine({required String line}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(line, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 5,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiSharedStateAppendLogLineConstMeta,
        argValues: [line],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSharedStateAppendLogLineConstMeta =>
      const TaskConstMeta(debugName: "append_log_line", argNames: ["line"]);

  @override
  Future<String> crateApiExchangeApproveDealBoardUsdc({
    required String mnemonic,
    required String amount,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(mnemonic, serializer);
          sse_encode_String(amount, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 6,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiExchangeApproveDealBoardUsdcConstMeta,
        argValues: [mnemonic, amount],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiExchangeApproveDealBoardUsdcConstMeta =>
      const TaskConstMeta(
        debugName: "approve_deal_board_usdc",
        argNames: ["mnemonic", "amount"],
      );

  @override
  Future<String> crateApiExchangeCheckEscrowStatus({required BigInt escrowId}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_u_64(escrowId, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 7,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiExchangeCheckEscrowStatusConstMeta,
        argValues: [escrowId],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiExchangeCheckEscrowStatusConstMeta =>
      const TaskConstMeta(
        debugName: "check_escrow_status",
        argNames: ["escrowId"],
      );

  @override
  Future<String> crateApiExchangeClaimExpiredEscrow({
    required String mnemonic,
    required BigInt escrowId,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(mnemonic, serializer);
          sse_encode_u_64(escrowId, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 8,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiExchangeClaimExpiredEscrowConstMeta,
        argValues: [mnemonic, escrowId],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiExchangeClaimExpiredEscrowConstMeta =>
      const TaskConstMeta(
        debugName: "claim_expired_escrow",
        argNames: ["mnemonic", "escrowId"],
      );

  @override
  Stream<String> crateApiTelemetryCreateLogStream() {
    final sink = RustStreamSink<String>();
    unawaited(
      handler.executeNormal(
        NormalTask(
          callFfi: (port_) {
            final serializer = SseSerializer(generalizedFrbRustBinding);
            sse_encode_StreamSink_String_Sse(sink, serializer);
            pdeCallFfi(
              generalizedFrbRustBinding,
              serializer,
              funcId: 9,
              port: port_,
            );
          },
          codec: SseCodec(
            decodeSuccessData: sse_decode_unit,
            decodeErrorData: null,
          ),
          constMeta: kCrateApiTelemetryCreateLogStreamConstMeta,
          argValues: [sink],
          apiImpl: this,
        ),
      ),
    );
    return sink.stream;
  }

  TaskConstMeta get kCrateApiTelemetryCreateLogStreamConstMeta =>
      const TaskConstMeta(debugName: "create_log_stream", argNames: ["sink"]);

  @override
  Future<String> crateApiExchangeCreateOffer({
    required String mnemonic,
    required BigInt agentId,
    required String endpointUrl,
    required List<String> protocols,
    required String region,
    required String pricePerGbRaw,
    required String stakeAmountRaw,
    required BigInt bandwidthMbps,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(mnemonic, serializer);
          sse_encode_u_64(agentId, serializer);
          sse_encode_String(endpointUrl, serializer);
          sse_encode_list_String(protocols, serializer);
          sse_encode_String(region, serializer);
          sse_encode_String(pricePerGbRaw, serializer);
          sse_encode_String(stakeAmountRaw, serializer);
          sse_encode_u_64(bandwidthMbps, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 10,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiExchangeCreateOfferConstMeta,
        argValues: [
          mnemonic,
          agentId,
          endpointUrl,
          protocols,
          region,
          pricePerGbRaw,
          stakeAmountRaw,
          bandwidthMbps,
        ],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiExchangeCreateOfferConstMeta =>
      const TaskConstMeta(
        debugName: "create_offer",
        argNames: [
          "mnemonic",
          "agentId",
          "endpointUrl",
          "protocols",
          "region",
          "pricePerGbRaw",
          "stakeAmountRaw",
          "bandwidthMbps",
        ],
      );

  @override
  String crateApiExchangeCreateWallet() {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 11)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiExchangeCreateWalletConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiExchangeCreateWalletConstMeta =>
      const TaskConstMeta(debugName: "create_wallet", argNames: []);

  @override
  Future<String> crateApiExchangeDeactivateOffer({
    required String mnemonic,
    required BigInt offerId,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(mnemonic, serializer);
          sse_encode_u_64(offerId, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 12,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiExchangeDeactivateOfferConstMeta,
        argValues: [mnemonic, offerId],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiExchangeDeactivateOfferConstMeta =>
      const TaskConstMeta(
        debugName: "deactivate_offer",
        argNames: ["mnemonic", "offerId"],
      );

  @override
  void crateApiCreditDismissNudge({required String nudgeId}) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(nudgeId, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 13)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiCreditDismissNudgeConstMeta,
        argValues: [nudgeId],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiCreditDismissNudgeConstMeta =>
      const TaskConstMeta(debugName: "dismiss_nudge", argNames: ["nudgeId"]);

  @override
  Stream<double> crateApiModelManagerDownloadModel({required String id}) {
    final progress = RustStreamSink<double>();
    unawaited(
      handler.executeNormal(
        NormalTask(
          callFfi: (port_) {
            final serializer = SseSerializer(generalizedFrbRustBinding);
            sse_encode_String(id, serializer);
            sse_encode_StreamSink_f_64_Sse(progress, serializer);
            pdeCallFfi(
              generalizedFrbRustBinding,
              serializer,
              funcId: 14,
              port: port_,
            );
          },
          codec: SseCodec(
            decodeSuccessData: sse_decode_unit,
            decodeErrorData: sse_decode_AnyhowException,
          ),
          constMeta: kCrateApiModelManagerDownloadModelConstMeta,
          argValues: [id, progress],
          apiImpl: this,
        ),
      ),
    );
    return progress.stream;
  }

  TaskConstMeta get kCrateApiModelManagerDownloadModelConstMeta =>
      const TaskConstMeta(
        debugName: "download_model",
        argNames: ["id", "progress"],
      );

  @override
  Future<String> crateApiContentFetchChannelMessages({
    required PlatformInt64 chatId,
    required int limit,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_i_64(chatId, serializer);
          sse_encode_i_32(limit, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 15,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiContentFetchChannelMessagesConstMeta,
        argValues: [chatId, limit],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiContentFetchChannelMessagesConstMeta =>
      const TaskConstMeta(
        debugName: "fetch_channel_messages",
        argNames: ["chatId", "limit"],
      );

  @override
  Future<String> crateApiSimpleGetActiveConnections() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 16,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiSimpleGetActiveConnectionsConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSimpleGetActiveConnectionsConstMeta =>
      const TaskConstMeta(debugName: "get_active_connections", argNames: []);

  @override
  Future<List<ModelInfo>> crateApiModelManagerGetAvailableModels() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 17,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_model_info,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiModelManagerGetAvailableModelsConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiModelManagerGetAvailableModelsConstMeta =>
      const TaskConstMeta(debugName: "get_available_models", argNames: []);

  @override
  Future<String> crateApiContentGetChatAttentionStats({
    required PlatformInt64 chatId,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_i_64(chatId, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 18,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiContentGetChatAttentionStatsConstMeta,
        argValues: [chatId],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiContentGetChatAttentionStatsConstMeta =>
      const TaskConstMeta(
        debugName: "get_chat_attention_stats",
        argNames: ["chatId"],
      );

  @override
  Future<String> crateApiSimpleGetConnectionStats() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 19,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiSimpleGetConnectionStatsConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSimpleGetConnectionStatsConstMeta =>
      const TaskConstMeta(debugName: "get_connection_stats", argNames: []);

  @override
  Future<String> crateApiCreditGetCreditStatus() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 20,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiCreditGetCreditStatusConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiCreditGetCreditStatusConstMeta =>
      const TaskConstMeta(debugName: "get_credit_status", argNames: []);

  @override
  Future<String> crateApiExchangeGetDealOffer({required BigInt offerId}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_u_64(offerId, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 21,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiExchangeGetDealOfferConstMeta,
        argValues: [offerId],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiExchangeGetDealOfferConstMeta =>
      const TaskConstMeta(debugName: "get_deal_offer", argNames: ["offerId"]);

  @override
  String crateApiExchangeGetMarketplaceConfigStatus() {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 22)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiExchangeGetMarketplaceConfigStatusConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiExchangeGetMarketplaceConfigStatusConstMeta =>
      const TaskConstMeta(
        debugName: "get_marketplace_config_status",
        argNames: [],
      );

  @override
  Future<String> crateApiContentGetMessageFoldContent({
    required String contentTreeJson,
    required int level,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(contentTreeJson, serializer);
          sse_encode_u_8(level, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 23,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiContentGetMessageFoldContentConstMeta,
        argValues: [contentTreeJson, level],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiContentGetMessageFoldContentConstMeta =>
      const TaskConstMeta(
        debugName: "get_message_fold_content",
        argNames: ["contentTreeJson", "level"],
      );

  @override
  Future<String> crateApiCreditGetNudge() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 24,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiCreditGetNudgeConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiCreditGetNudgeConstMeta =>
      const TaskConstMeta(debugName: "get_nudge", argNames: []);

  @override
  Future<String> crateApiProviderGetProviderEarnings() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 25,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiProviderGetProviderEarningsConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiProviderGetProviderEarningsConstMeta =>
      const TaskConstMeta(debugName: "get_provider_earnings", argNames: []);

  @override
  Future<(BigInt, BigInt)> crateApiQuotaGetQuotaRaw() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 26,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_record_u_64_u_64,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiQuotaGetQuotaRawConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiQuotaGetQuotaRawConstMeta =>
      const TaskConstMeta(debugName: "get_quota_raw", argNames: []);

  @override
  Future<String> crateApiQuotaGetQuotaStatus() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 27,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiQuotaGetQuotaStatusConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiQuotaGetQuotaStatusConstMeta =>
      const TaskConstMeta(debugName: "get_quota_status", argNames: []);

  @override
  Future<String> crateApiProviderGetShareEarnStatus() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 28,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiProviderGetShareEarnStatusConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiProviderGetShareEarnStatusConstMeta =>
      const TaskConstMeta(debugName: "get_share_earn_status", argNames: []);

  @override
  Future<String> crateApiCreditGetTelegramAnchorInfo() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 29,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiCreditGetTelegramAnchorInfoConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiCreditGetTelegramAnchorInfoConstMeta =>
      const TaskConstMeta(debugName: "get_telegram_anchor_info", argNames: []);

  @override
  Future<String> crateApiExchangeGetWalletBalances({required String address}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(address, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 30,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiExchangeGetWalletBalancesConstMeta,
        argValues: [address],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiExchangeGetWalletBalancesConstMeta =>
      const TaskConstMeta(
        debugName: "get_wallet_balances",
        argNames: ["address"],
      );

  @override
  String crateApiExchangeGetWalletPreview({required String mnemonic}) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(mnemonic, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 31)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiExchangeGetWalletPreviewConstMeta,
        argValues: [mnemonic],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiExchangeGetWalletPreviewConstMeta =>
      const TaskConstMeta(
        debugName: "get_wallet_preview",
        argNames: ["mnemonic"],
      );

  @override
  String crateApiSimpleGreet({required String name}) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(name, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 32)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiSimpleGreetConstMeta,
        argValues: [name],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSimpleGreetConstMeta =>
      const TaskConstMeta(debugName: "greet", argNames: ["name"]);

  @override
  String crateApiExchangeImportWallet({required String mnemonic}) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(mnemonic, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 33)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiExchangeImportWalletConstMeta,
        argValues: [mnemonic],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiExchangeImportWalletConstMeta =>
      const TaskConstMeta(debugName: "import_wallet", argNames: ["mnemonic"]);

  @override
  Future<void> crateApiSimpleInitApp() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 34,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiSimpleInitAppConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSimpleInitAppConstMeta =>
      const TaskConstMeta(debugName: "init_app", argNames: []);

  @override
  Future<void> crateApiContentInitContentEngine({required String baseDir}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(baseDir, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 35,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiContentInitContentEngineConstMeta,
        argValues: [baseDir],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiContentInitContentEngineConstMeta =>
      const TaskConstMeta(
        debugName: "init_content_engine",
        argNames: ["baseDir"],
      );

  @override
  Future<void> crateApiSimpleInitExtensionRuntime({required String baseDir}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(baseDir, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 36,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiSimpleInitExtensionRuntimeConstMeta,
        argValues: [baseDir],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSimpleInitExtensionRuntimeConstMeta =>
      const TaskConstMeta(
        debugName: "init_extension_runtime",
        argNames: ["baseDir"],
      );

  @override
  void crateApiModelManagerInitModelManager({required String baseDir}) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(baseDir, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 37)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiModelManagerInitModelManagerConstMeta,
        argValues: [baseDir],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiModelManagerInitModelManagerConstMeta =>
      const TaskConstMeta(
        debugName: "init_model_manager",
        argNames: ["baseDir"],
      );

  @override
  Future<void> crateApiQuotaInitQuota({
    required String relayUrl,
    required String deviceId,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(relayUrl, serializer);
          sse_encode_String(deviceId, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 38,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiQuotaInitQuotaConstMeta,
        argValues: [relayUrl, deviceId],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiQuotaInitQuotaConstMeta => const TaskConstMeta(
    debugName: "init_quota",
    argNames: ["relayUrl", "deviceId"],
  );

  @override
  Future<String> crateApiExchangeListDealOffers({required String currency}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(currency, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 39,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiExchangeListDealOffersConstMeta,
        argValues: [currency],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiExchangeListDealOffersConstMeta =>
      const TaskConstMeta(
        debugName: "list_deal_offers",
        argNames: ["currency"],
      );

  @override
  Future<String> crateApiExchangeListRouteOffers({
    required String region,
    required String protocol,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(region, serializer);
          sse_encode_String(protocol, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 40,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiExchangeListRouteOffersConstMeta,
        argValues: [region, protocol],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiExchangeListRouteOffersConstMeta =>
      const TaskConstMeta(
        debugName: "list_route_offers",
        argNames: ["region", "protocol"],
      );

  @override
  Future<String> crateApiExchangeMarkFiatSent({
    required String mnemonic,
    required BigInt escrowId,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(mnemonic, serializer);
          sse_encode_u_64(escrowId, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 41,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiExchangeMarkFiatSentConstMeta,
        argValues: [mnemonic, escrowId],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiExchangeMarkFiatSentConstMeta =>
      const TaskConstMeta(
        debugName: "mark_fiat_sent",
        argNames: ["mnemonic", "escrowId"],
      );

  @override
  Future<void> crateApiSharedStatePersistActiveConnections({
    required String json,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(json, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 42,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiSharedStatePersistActiveConnectionsConstMeta,
        argValues: [json],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSharedStatePersistActiveConnectionsConstMeta =>
      const TaskConstMeta(
        debugName: "persist_active_connections",
        argNames: ["json"],
      );

  @override
  Future<void> crateApiSharedStatePersistConnectionStats({
    required String json,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(json, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 43,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiSharedStatePersistConnectionStatsConstMeta,
        argValues: [json],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSharedStatePersistConnectionStatsConstMeta =>
      const TaskConstMeta(
        debugName: "persist_connection_stats",
        argNames: ["json"],
      );

  @override
  Future<void> crateApiSharedStatePersistQuotaStatus({required String json}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(json, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 44,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiSharedStatePersistQuotaStatusConstMeta,
        argValues: [json],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSharedStatePersistQuotaStatusConstMeta =>
      const TaskConstMeta(
        debugName: "persist_quota_status",
        argNames: ["json"],
      );

  @override
  Future<void> crateApiSimplePrepareLocalRuntime({required String baseDir}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(baseDir, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 45,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiSimplePrepareLocalRuntimeConstMeta,
        argValues: [baseDir],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSimplePrepareLocalRuntimeConstMeta =>
      const TaskConstMeta(
        debugName: "prepare_local_runtime",
        argNames: ["baseDir"],
      );

  @override
  Future<List<String>> crateApiSharedStateReadLogLines() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 46,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_String,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiSharedStateReadLogLinesConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSharedStateReadLogLinesConstMeta =>
      const TaskConstMeta(debugName: "read_log_lines", argNames: []);

  @override
  Future<void> crateApiContentRecordAttention({
    required String messageId,
    required PlatformInt64 chatId,
    required int maxDepth,
    required BigInt readTimeMs,
    required String interaction,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(messageId, serializer);
          sse_encode_i_64(chatId, serializer);
          sse_encode_u_8(maxDepth, serializer);
          sse_encode_u_64(readTimeMs, serializer);
          sse_encode_String(interaction, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 47,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiContentRecordAttentionConstMeta,
        argValues: [messageId, chatId, maxDepth, readTimeMs, interaction],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiContentRecordAttentionConstMeta =>
      const TaskConstMeta(
        debugName: "record_attention",
        argNames: [
          "messageId",
          "chatId",
          "maxDepth",
          "readTimeMs",
          "interaction",
        ],
      );

  @override
  Future<void> crateApiQuotaRecordBytes({required BigInt bytes}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_u_64(bytes, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 48,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiQuotaRecordBytesConstMeta,
        argValues: [bytes],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiQuotaRecordBytesConstMeta =>
      const TaskConstMeta(debugName: "record_bytes", argNames: ["bytes"]);

  @override
  Future<String> crateApiExchangeRegisterAgent({required String mnemonic}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(mnemonic, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 49,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiExchangeRegisterAgentConstMeta,
        argValues: [mnemonic],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiExchangeRegisterAgentConstMeta =>
      const TaskConstMeta(debugName: "register_agent", argNames: ["mnemonic"]);

  @override
  Future<void> crateApiQuotaResetDailyQuota() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 50,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiQuotaResetDailyQuotaConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiQuotaResetDailyQuotaConstMeta =>
      const TaskConstMeta(debugName: "reset_daily_quota", argNames: []);

  @override
  Future<void> crateApiModelManagerSetActiveModel({required String id}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(id, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 51,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiModelManagerSetActiveModelConstMeta,
        argValues: [id],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiModelManagerSetActiveModelConstMeta =>
      const TaskConstMeta(debugName: "set_active_model", argNames: ["id"]);

  @override
  Future<void> crateApiSimpleSetConnectionProxy({
    required BigInt connId,
    required bool proxied,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_u_64(connId, serializer);
          sse_encode_bool(proxied, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 52,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiSimpleSetConnectionProxyConstMeta,
        argValues: [connId, proxied],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSimpleSetConnectionProxyConstMeta =>
      const TaskConstMeta(
        debugName: "set_connection_proxy",
        argNames: ["connId", "proxied"],
      );

  @override
  Future<void> crateApiSimpleSetProxyMode({required String mode}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(mode, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 53,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiSimpleSetProxyModeConstMeta,
        argValues: [mode],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSimpleSetProxyModeConstMeta =>
      const TaskConstMeta(debugName: "set_proxy_mode", argNames: ["mode"]);

  @override
  Future<String> crateApiProviderSetShareEarnEnabled({
    required bool enabled,
    String? mnemonic,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_bool(enabled, serializer);
          sse_encode_opt_String(mnemonic, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 54,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiProviderSetShareEarnEnabledConstMeta,
        argValues: [enabled, mnemonic],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiProviderSetShareEarnEnabledConstMeta =>
      const TaskConstMeta(
        debugName: "set_share_earn_enabled",
        argNames: ["enabled", "mnemonic"],
      );

  @override
  Future<String> crateApiSharedStateSnapshotJson() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 55,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiSharedStateSnapshotJsonConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSharedStateSnapshotJsonConstMeta =>
      const TaskConstMeta(debugName: "snapshot_json", argNames: []);

  @override
  Future<void> crateApiSimpleStartHydraNode({required String baseDir}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(baseDir, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 56,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiSimpleStartHydraNodeConstMeta,
        argValues: [baseDir],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSimpleStartHydraNodeConstMeta =>
      const TaskConstMeta(debugName: "start_hydra_node", argNames: ["baseDir"]);

  @override
  void crateApiVpnStartVpnTunnel({required int fd}) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_i_32(fd, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 57)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiVpnStartVpnTunnelConstMeta,
        argValues: [fd],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiVpnStartVpnTunnelConstMeta =>
      const TaskConstMeta(debugName: "start_vpn_tunnel", argNames: ["fd"]);

  @override
  void crateApiVpnStopVpnTunnel() {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 58)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiVpnStopVpnTunnelConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiVpnStopVpnTunnelConstMeta =>
      const TaskConstMeta(debugName: "stop_vpn_tunnel", argNames: []);

  @override
  Future<String> crateApiExchangeSubmitFeedback({
    required String mnemonic,
    required BigInt agentId,
    required bool positive,
    required String tag1,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(mnemonic, serializer);
          sse_encode_u_64(agentId, serializer);
          sse_encode_bool(positive, serializer);
          sse_encode_String(tag1, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 59,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiExchangeSubmitFeedbackConstMeta,
        argValues: [mnemonic, agentId, positive, tag1],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiExchangeSubmitFeedbackConstMeta =>
      const TaskConstMeta(
        debugName: "submit_feedback",
        argNames: ["mnemonic", "agentId", "positive", "tag1"],
      );

  @override
  Future<String> crateApiQuotaSyncQuotaWithServer() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 60,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiQuotaSyncQuotaWithServerConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiQuotaSyncQuotaWithServerConstMeta =>
      const TaskConstMeta(debugName: "sync_quota_with_server", argNames: []);

  @override
  Future<String> crateApiContentTelegramAuthState() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 61,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiContentTelegramAuthStateConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiContentTelegramAuthStateConstMeta =>
      const TaskConstMeta(debugName: "telegram_auth_state", argNames: []);

  @override
  Future<String> crateApiContentTelegramConnect() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 62,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiContentTelegramConnectConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiContentTelegramConnectConstMeta =>
      const TaskConstMeta(debugName: "telegram_connect", argNames: []);

  @override
  Future<void> crateApiContentTelegramDisconnect() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 63,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiContentTelegramDisconnectConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiContentTelegramDisconnectConstMeta =>
      const TaskConstMeta(debugName: "telegram_disconnect", argNames: []);

  @override
  Future<String> crateApiContentTelegramGetDialogs() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 64,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiContentTelegramGetDialogsConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiContentTelegramGetDialogsConstMeta =>
      const TaskConstMeta(debugName: "telegram_get_dialogs", argNames: []);

  @override
  Future<String> crateApiContentTelegramSendCode({required String code}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(code, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 65,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiContentTelegramSendCodeConstMeta,
        argValues: [code],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiContentTelegramSendCodeConstMeta =>
      const TaskConstMeta(debugName: "telegram_send_code", argNames: ["code"]);

  @override
  Future<String> crateApiContentTelegramSendPassword({
    required String password,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(password, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 66,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiContentTelegramSendPasswordConstMeta,
        argValues: [password],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiContentTelegramSendPasswordConstMeta =>
      const TaskConstMeta(
        debugName: "telegram_send_password",
        argNames: ["password"],
      );

  @override
  Future<String> crateApiContentTelegramSendPhone({required String phone}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(phone, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 67,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiContentTelegramSendPhoneConstMeta,
        argValues: [phone],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiContentTelegramSendPhoneConstMeta =>
      const TaskConstMeta(
        debugName: "telegram_send_phone",
        argNames: ["phone"],
      );

  @override
  Future<String> crateApiProviderUpdateShareSettings({
    String? priceOverrideRaw,
    BigInt? maxBandwidthMbps,
    required bool wifiOnly,
    int? scheduleStartHour,
    int? scheduleEndHour,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_opt_String(priceOverrideRaw, serializer);
          sse_encode_opt_box_autoadd_u_64(maxBandwidthMbps, serializer);
          sse_encode_bool(wifiOnly, serializer);
          sse_encode_opt_box_autoadd_u_8(scheduleStartHour, serializer);
          sse_encode_opt_box_autoadd_u_8(scheduleEndHour, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 68,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiProviderUpdateShareSettingsConstMeta,
        argValues: [
          priceOverrideRaw,
          maxBandwidthMbps,
          wifiOnly,
          scheduleStartHour,
          scheduleEndHour,
        ],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiProviderUpdateShareSettingsConstMeta =>
      const TaskConstMeta(
        debugName: "update_share_settings",
        argNames: [
          "priceOverrideRaw",
          "maxBandwidthMbps",
          "wifiOnly",
          "scheduleStartHour",
          "scheduleEndHour",
        ],
      );

  @override
  Future<String> crateApiExchangeWithdrawStake({
    required String mnemonic,
    required BigInt offerId,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(mnemonic, serializer);
          sse_encode_u_64(offerId, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 69,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiExchangeWithdrawStakeConstMeta,
        argValues: [mnemonic, offerId],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiExchangeWithdrawStakeConstMeta =>
      const TaskConstMeta(
        debugName: "withdraw_stake",
        argNames: ["mnemonic", "offerId"],
      );

  @protected
  AnyhowException dco_decode_AnyhowException(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return AnyhowException(raw as String);
  }

  @protected
  RustStreamSink<String> dco_decode_StreamSink_String_Sse(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    throw UnimplementedError();
  }

  @protected
  RustStreamSink<double> dco_decode_StreamSink_f_64_Sse(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    throw UnimplementedError();
  }

  @protected
  String dco_decode_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as String;
  }

  @protected
  bool dco_decode_bool(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as bool;
  }

  @protected
  BigInt dco_decode_box_autoadd_u_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_u_64(raw);
  }

  @protected
  int dco_decode_box_autoadd_u_8(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  double dco_decode_f_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as double;
  }

  @protected
  int dco_decode_i_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  PlatformInt64 dco_decode_i_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dcoDecodeI64(raw);
  }

  @protected
  List<String> dco_decode_list_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_String).toList();
  }

  @protected
  List<ModelInfo> dco_decode_list_model_info(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_model_info).toList();
  }

  @protected
  Uint8List dco_decode_list_prim_u_8_strict(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as Uint8List;
  }

  @protected
  ModelInfo dco_decode_model_info(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 6)
      throw Exception('unexpected arr length: expect 6 but see ${arr.length}');
    return ModelInfo(
      id: dco_decode_String(arr[0]),
      name: dco_decode_String(arr[1]),
      description: dco_decode_String(arr[2]),
      sizeMb: dco_decode_u_32(arr[3]),
      downloadUrl: dco_decode_String(arr[4]),
      isDownloaded: dco_decode_bool(arr[5]),
    );
  }

  @protected
  String? dco_decode_opt_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_String(raw);
  }

  @protected
  BigInt? dco_decode_opt_box_autoadd_u_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_box_autoadd_u_64(raw);
  }

  @protected
  int? dco_decode_opt_box_autoadd_u_8(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_box_autoadd_u_8(raw);
  }

  @protected
  (BigInt, BigInt) dco_decode_record_u_64_u_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 2) {
      throw Exception('Expected 2 elements, got ${arr.length}');
    }
    return (dco_decode_u_64(arr[0]), dco_decode_u_64(arr[1]));
  }

  @protected
  int dco_decode_u_16(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  int dco_decode_u_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  BigInt dco_decode_u_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dcoDecodeU64(raw);
  }

  @protected
  int dco_decode_u_8(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  void dco_decode_unit(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return;
  }

  @protected
  AnyhowException sse_decode_AnyhowException(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_String(deserializer);
    return AnyhowException(inner);
  }

  @protected
  RustStreamSink<String> sse_decode_StreamSink_String_Sse(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    throw UnimplementedError('Unreachable ()');
  }

  @protected
  RustStreamSink<double> sse_decode_StreamSink_f_64_Sse(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    throw UnimplementedError('Unreachable ()');
  }

  @protected
  String sse_decode_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_list_prim_u_8_strict(deserializer);
    return utf8.decoder.convert(inner);
  }

  @protected
  bool sse_decode_bool(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8() != 0;
  }

  @protected
  BigInt sse_decode_box_autoadd_u_64(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_u_64(deserializer));
  }

  @protected
  int sse_decode_box_autoadd_u_8(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_u_8(deserializer));
  }

  @protected
  double sse_decode_f_64(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getFloat64();
  }

  @protected
  int sse_decode_i_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getInt32();
  }

  @protected
  PlatformInt64 sse_decode_i_64(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getPlatformInt64();
  }

  @protected
  List<String> sse_decode_list_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <String>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_String(deserializer));
    }
    return ans_;
  }

  @protected
  List<ModelInfo> sse_decode_list_model_info(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <ModelInfo>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_model_info(deserializer));
    }
    return ans_;
  }

  @protected
  Uint8List sse_decode_list_prim_u_8_strict(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var len_ = sse_decode_i_32(deserializer);
    return deserializer.buffer.getUint8List(len_);
  }

  @protected
  ModelInfo sse_decode_model_info(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_id = sse_decode_String(deserializer);
    var var_name = sse_decode_String(deserializer);
    var var_description = sse_decode_String(deserializer);
    var var_sizeMb = sse_decode_u_32(deserializer);
    var var_downloadUrl = sse_decode_String(deserializer);
    var var_isDownloaded = sse_decode_bool(deserializer);
    return ModelInfo(
      id: var_id,
      name: var_name,
      description: var_description,
      sizeMb: var_sizeMb,
      downloadUrl: var_downloadUrl,
      isDownloaded: var_isDownloaded,
    );
  }

  @protected
  String? sse_decode_opt_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_String(deserializer));
    } else {
      return null;
    }
  }

  @protected
  BigInt? sse_decode_opt_box_autoadd_u_64(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_box_autoadd_u_64(deserializer));
    } else {
      return null;
    }
  }

  @protected
  int? sse_decode_opt_box_autoadd_u_8(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_box_autoadd_u_8(deserializer));
    } else {
      return null;
    }
  }

  @protected
  (BigInt, BigInt) sse_decode_record_u_64_u_64(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_field0 = sse_decode_u_64(deserializer);
    var var_field1 = sse_decode_u_64(deserializer);
    return (var_field0, var_field1);
  }

  @protected
  int sse_decode_u_16(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint16();
  }

  @protected
  int sse_decode_u_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint32();
  }

  @protected
  BigInt sse_decode_u_64(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getBigUint64();
  }

  @protected
  int sse_decode_u_8(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8();
  }

  @protected
  void sse_decode_unit(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }

  @protected
  void sse_encode_AnyhowException(
    AnyhowException self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.message, serializer);
  }

  @protected
  void sse_encode_StreamSink_String_Sse(
    RustStreamSink<String> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(
      self.setupAndSerialize(
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: sse_decode_AnyhowException,
        ),
      ),
      serializer,
    );
  }

  @protected
  void sse_encode_StreamSink_f_64_Sse(
    RustStreamSink<double> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(
      self.setupAndSerialize(
        codec: SseCodec(
          decodeSuccessData: sse_decode_f_64,
          decodeErrorData: sse_decode_AnyhowException,
        ),
      ),
      serializer,
    );
  }

  @protected
  void sse_encode_String(String self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_list_prim_u_8_strict(utf8.encoder.convert(self), serializer);
  }

  @protected
  void sse_encode_bool(bool self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self ? 1 : 0);
  }

  @protected
  void sse_encode_box_autoadd_u_64(BigInt self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_u_64(self, serializer);
  }

  @protected
  void sse_encode_box_autoadd_u_8(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_u_8(self, serializer);
  }

  @protected
  void sse_encode_f_64(double self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putFloat64(self);
  }

  @protected
  void sse_encode_i_32(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putInt32(self);
  }

  @protected
  void sse_encode_i_64(PlatformInt64 self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putPlatformInt64(self);
  }

  @protected
  void sse_encode_list_String(List<String> self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_String(item, serializer);
    }
  }

  @protected
  void sse_encode_list_model_info(
    List<ModelInfo> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_model_info(item, serializer);
    }
  }

  @protected
  void sse_encode_list_prim_u_8_strict(
    Uint8List self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    serializer.buffer.putUint8List(self);
  }

  @protected
  void sse_encode_model_info(ModelInfo self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.id, serializer);
    sse_encode_String(self.name, serializer);
    sse_encode_String(self.description, serializer);
    sse_encode_u_32(self.sizeMb, serializer);
    sse_encode_String(self.downloadUrl, serializer);
    sse_encode_bool(self.isDownloaded, serializer);
  }

  @protected
  void sse_encode_opt_String(String? self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_String(self, serializer);
    }
  }

  @protected
  void sse_encode_opt_box_autoadd_u_64(BigInt? self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_box_autoadd_u_64(self, serializer);
    }
  }

  @protected
  void sse_encode_opt_box_autoadd_u_8(int? self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_box_autoadd_u_8(self, serializer);
    }
  }

  @protected
  void sse_encode_record_u_64_u_64(
    (BigInt, BigInt) self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_u_64(self.$1, serializer);
    sse_encode_u_64(self.$2, serializer);
  }

  @protected
  void sse_encode_u_16(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint16(self);
  }

  @protected
  void sse_encode_u_32(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint32(self);
  }

  @protected
  void sse_encode_u_64(BigInt self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putBigUint64(self);
  }

  @protected
  void sse_encode_u_8(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self);
  }

  @protected
  void sse_encode_unit(void self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }
}
