[package]
name = "hydra-p2p"
version = "0.1.0"
edition = "2024"

[dependencies]
hydra-config = { path = "../hydra-config" }
libp2p = { workspace = true }
libp2p-stream = { workspace = true }
tokio = { workspace = true }
tokio-util = { workspace = true }
anyhow = { workspace = true }
thiserror = { workspace = true }
tracing = { workspace = true }
serde.workspace = true
serde_json.workspace = true
futures = "0.3"
async-trait = "0.1.89"
